### PR TITLE
Create a zarr with masks for an idr0041 image

### PR DESCRIPTION
**Pull request by manics**

### CODE REVIEW

**Comment by joshmoore** [comment]
Some through reading through the notebook:
 - See https://github.com/ome/omero-ms-zarr/pull/51 -- I imagine you could use `!omero zarr export` directly from the notebook.
 - Having the names is definitely nice (though there are probably limits on which characters could be used), but that wouldn't work with a labelled image, right?
 - This example uses the "rois are images" strategy. Have your scripts for turning such images into ROIs/Shapes set the names? i.e. will it work for the other strategy?

**Comment by manics** [comment]
The `--group-rois` flag in https://github.com/ome/omero-cli-zarr/pull/8 should support this format which is required if you've got overlapping ROIs. The main issue would be how to obtain the name- we'd need a convention for how it's stored in OMERO e.g. `Roi.name`?

**Comment by joshmoore** [comment]
> we'd need a convention for how it's stored in OMERO e.g. `Roi.name`?

I guess so, since `Shape` doesn't have a name field. Would these then be stored as another array with all the names?

**Comment by joshmoore** [comment]
@manics: what do you want to happen here?

**Comment by manics** [comment]
See https://github.com/IDR/idr0041-cai-mitoticatlas/issues/19

**Pull request closed without merging**
