### PR TITLE
Plate multiscales

### PR DESCRIPTION
**Pull request by will-moore**
On top of #28.

Adds multiresolutions for each Image, scaling each 2D plane down by a factor of 2, until smaller than 96 on longest side.

NB: this doesn't use ome-zarr-py to do the scaling (but uses the same underlying cv2 method) because we're scaling a 2D plane each time, not 5D.

cc @sbesson, @dominikl, @joshmoore 

TODO:
 - Add arguments to allow you to turn this on/off and to choose target size (and to choose scaling method?)

### CODE REVIEW

**Comment by joshmoore** [comment]
With the additional commits, https://github.com/ome/ome-zarr-py/pull/56 shows:

```
ome_zarr info 1.zarr/
/private/tmp/1.zarr [zgroup]
 - metadata
   - Plate
 - data
/private/tmp/1.zarr/PlateAcquisition Name 0/A/1/Field_1 [zgroup]
 - metadata
   - Multiscales
   - OMERO
 - data
   - (1, 1, 1, 512, 512)
   - (1, 1, 1, 256, 256)
   - (1, 1, 1, 128, 128)
   - (1, 1, 1, 64, 64)
```

**Comment by joshmoore** [comment]
@dominikl : do you want to take care of the linting failure in your follow up PR?

**Comment by joshmoore** [comment]
Got an "ok" elsewhere. Merging to be fixed in the follow-up.

**Comment by sbesson** [comment]
4d7850d was tested against the first illumination corrected plate of idr0033 using the following Docker pipeline

```
FROM centos:7

RUN yum install -y git python3 fontconfig

RUN useradd -ms /bin/bash converter
USER converter

RUN python3 -m venv /tmp/venv && /tmp/venv/bin/pip install -U pip wheel && /tmp/venv/bin/pip install https://github.com/ome/zeroc-ice-py-centos7/releases/download/0.2.1/zeroc_ice-3.6.5-cp36-cp36m-linux_x86_64.whl
RUN /tmp/venv/bin/pip install ome-zarr scikit-image omero-py
RUN /tmp/venv/bin/pip install git+https://github.com/will-moore/omero-cli-zarr@plate_multiscales

RUN /tmp/venv/bin/omero login public@idr.openmicroscopy.org -w public
ENTRYPOINT ["/tmp/venv/bin/omero", "zarr", "--output", "/data/41744_illum_corrected/", "export", "Plate:5966"]
```

It should be straightforward to adjust the pip install command to consume the `master` branch/any branch and reconvert the data including to include the `omero` metadata. #30 should simplify the installation step but is not a requirement. /cc @will-moore

**Pull request merged**
