### PR TITLE
Fix units -> unit

### PR DESCRIPTION
**Pull request by will-moore**
See https://github.com/ome/ngff/pull/157

This is a corresponding fix to update all axes "units" to "unit" (as in the Spec).

### CODE REVIEW

**Review by sbesson — APPROVED** [review]
Sounds like we should schedule an immediate patch release to ensure the unit metadata is written correctly. Is https://github.com/ome/ome-zarr-py/releases/tag/v0.6.1 used anywhere as we probably want to avoid creating mixed data types as well?

**Comment by joshmoore** [comment]
:+1: for getting this out ASAP.

**Comment by will-moore** [comment]
@sbesson I checked all the samples at https://idr.github.io/ome-ngff-samples/ for mixed dtypes but didn't see any.
I think `scaler.local_mean()` isn't used by `omero-cli-zarr` as it uses from `skimage.transform.resize` directly.

**Comment by will-moore** [comment]
Released as `omero-cli-zarr 0.5.1`

**Pull request merged**
